#define BC_T_PERIODIC
#define BC_X_PERIODIC
#define BC_Y_PERIODIC
#define BC_Z_PERIODIC
#define NDEBUG
#define IO_FLUSH
#define REPR_FUNDAMENTAL
#define REPR_NAME "REPR_FUNDAMENTAL"
#define GAUGE_SUN

